### ISSUE TITLE
macOS version of .VFF Downloader?

### ISSUE THREAD

**Issue by HilbertIdeals5** [RiiConnect24/.VFF-File-Downloader-for-Dolphin#10]
I want to run Dolphin with RiiConnect24 on my M1 MacBook Air, but since the .VFF Downloader is a .bat file that's only for Windows, I was wondering if it would be possible to make a Mac version? I don't know how much of a task that would be, but since it's a .bat file, which is kind of like a shell script in my experience, maybe it would be possible?

**Comment by Artuto** [comment]
None of us Developers have enough knowledge on making a shell script for Unix systems.

If someone is willing to do it they can PR it here.

**Comment by KcrPL** [comment]
The only thing that script does is download few files and put them to a specific location. It's not hard :)
