### ISSUE TITLE
Wrong path gets detected if user is using Microsoft Account instead of local account.

### ISSUE THREAD

**Issue by KcrPL** [RiiConnect24/.VFF-File-Downloader-for-Dolphin#16]
Install.bat uses the default `%USERPROFILE%\Documents\Dolphin Emulator\Wii\title\00010002` path instead of `C:\Users\<username>\OneDrive\Documents\Dolphin Emulator\Wii\title\00010002` when logged in using Microsoft Account.

**Comment by Artuto** [comment]
Why the fuck are you storing such files on OneDrive

**Comment by noahpistilli** [comment]
Is this really a bug, or someone who has OneDrive on

**Comment by KcrPL** [comment]
Ask Microsoft why they're storing these files on OneDrive by default. Dolphin just stores files in Documents folder.

**Comment by KcrPL** [comment]
Fixed in 5e033014cfdd1bc1a1ee5eae82bf10cd1758b479
- Fix the patcher detecting incorrect path when using a Microsoft Account instead of a local account.
