### ISSUE TITLE
Windows Defender classifies program as a PUP

### ISSUE THREAD

**Issue by cannon9009** [RiiConnect24/.VFF-File-Downloader-for-Dolphin#17]
Windows Defender is classifying this program as a Potentially Unwanted Software called Cayunamer.A!ml. Should I notify Windows Support that this mark is false?

**Comment by TheShadowEevee** [comment]
This is indeed a false positive; I have reported it to Microsoft already so it's up to you if you want to report it; more reports can only help.

**Comment by noahpistilli** [comment]
Closing.
