### ISSUE TITLE
FORE000006 error on dolphin

### ISSUE THREAD

**Issue by nonogamer9** [RiiConnect24/.VFF-File-Downloader-for-Dolphin#18]
the news channel works for me but forecast channel keeps doing error FORE000006

**Comment by ghost** [comment]
same

**Comment by mason1412** [comment]
i found a way to bruteforce it and it is to basically reopen installer and then if you do manual hit 3 but if you dont idfk about your situation but you have to do it everytime

**Comment by KcrPL** [comment]
FORE000006 is unfortunately an emulation issue on Dolphin. We don't know how to fix it. Sometimes it works, sometimes it doesn't. Closing.

**Comment by noahpistilli** [comment]
> i found a way to bruteforce it and it is to basically reopen installer and then if you do manual hit 3 but if you dont idfk about your situation but you have to do it everytime

Downloading a file isn't brute forcing

**Comment by ghost** [comment]
Edit: now its FORE000005

Op ma 8 nov. 2021 16:45 schreef Sketch ***@***.***>:
