### ISSUE TITLE
FORE000006

### ISSUE THREAD

**Issue by KawaiiTemDev** [RiiConnect24/.VFF-File-Downloader-for-Dolphin#19]
News channel is working.
Forecast channel doesn't work

**Comment by KcrPL** [comment]
This is an issue with Dolphin's emulation. Something isn't accurate and the emulator thinks the timestamp is incorrect, therefore returning error FORE000006. Sometimes it works, sometimes it doesn't.

There's nothing we can do about it. News Channel doesn't check the timestamp. The file can even be 10 years old and it will load just fine. Forecast Channel data expires every hour.
