### ISSUE TITLE
Argentina not working

### ISSUE THREAD

**Issue by ghost** [RiiConnect24/.VFF-File-Downloader-for-Dolphin#2]
When i type 010(argentina code), it says its incorrect the number i typed

**Comment by Dinosaurismus** [comment]
https://github.com/RiiConnect24/.VFF-File-Downloader-for-Dolphin/blob/f34f22c063189be706c3f1552d654cf43bf2e666/Install.bat#L574-L579
Oh of course, they forgot to add a check for Argentina. Fixing it would be as simple as adding this line to it:
```batch
if "%region%"=="010" set region_name=Argentina
```

**Comment by Peter0x44** [comment]
then submit a PR, so KcrPL can merge it

**Comment by KcrPL** [comment]
Well, looks like I missed it.

It happens, heh.
I'll fix it in the next update.

**Comment by ghost** [comment]
Ok, ty! I should close this thread?

**Comment by KcrPL** [comment]
I'll close it when I'll fix it :)

**Comment by KcrPL** [comment]
Fixed in update v1.0.6
