### ISSUE TITLE
Change filename for Windows

### ISSUE THREAD

**Issue by osfanbuff63** [RiiConnect24/.VFF-File-Downloader-for-Dolphin#21]
Currently, you have to unblock the batch file from the file's properties on Windows to let it run. I believe (but do not know), that this is in part because the file name was recently changed from `.VFF-File-Downloader-For-Dolphin.bat` to `Install.bat`, which looks much more suspicious of a file name. Could this change be reverted? Especially since the changelog tells you to download `.VFF-File-Downloader-For-Dolphin.bat` on Windows when there is no asset named this.

**Comment by KcrPL** [comment]
This tool will be deprecated soon. No point in doing it now.

**Comment by osfanbuff63** [comment]
Yeah, that's why I closed it :P
