### ISSUE TITLE
The Forecast Channel is not working.

### ISSUE THREAD

**Issue by ghost** [RiiConnect24/.VFF-File-Downloader-for-Dolphin#4]
When I start the Forecast Channel, I only get the error FORE000006.

I have already tried to deactivate my Antivirus program and tried again to install the .VFF file for Dolphin but that didn't help.

Dolphin Emulator [5.0-11824]
Wii system version [4.3E]

**Comment by ghost** [comment]
happens to me also.

**Comment by KcrPL** [comment]
It's an issue with Dolphin, the program itself is working.
And since we're not the developers of Dolphin - there's nothing we can do.

Closing.

**Comment by dakrk** [comment]
> "works with the forecast channel"

>  actually doesn't

trolled

**Comment by KcrPL** [comment]
For some it works, for some it doesn't ¯\_(ツ)_/¯
