### ISSUE TITLE
Windows 10: VFF-Downloader-For-Dolphin.exe marked as Trojan

### ISSUE THREAD

**Issue by simsnet** [RiiConnect24/.VFF-File-Downloader-for-Dolphin#5]
A recent virus scan with Windows Defender revealed that the VFF downloader executable is a trojan known as "Wacatac.D3!ml".  Should my AV be throwing these errors?  I have seen some software, such as NirSoft utilities, throw all sorts of malware warnings due to their "hacking" functions and system-level tasks.

**Comment by Artuto** [comment]
Most of the AV's mark it as fine: https://www.virustotal.com/gui/file/9531e10c648f08b42fccc6a3c49aa50c9b2f9498ca326b008900c367ac49bd7a/detection

The source of the batch file is also in this repository.

**Comment by KcrPL** [comment]
I need to contact Microsoft again so they can mark it as safe.

Anyway, there's not much I can do. It's the program that converts it.

Closing.
