### ISSUE TITLE
VFF downloader crashes when trying to check my user files

### ISSUE THREAD

**Issue by YousifAlkhalaf** [RiiConnect24/.VFF-File-Downloader-for-Dolphin#8]
When I try to run Install.bat, I can start it but when proceeding to try to check my user files, it crashes and closes itself.

**Comment by KcrPL** [comment]
Alright, Windows 7 or 10?

**Comment by YousifAlkhalaf** [comment]
Windows 10

**Comment by YousifAlkhalaf** [comment]
Idk if this is related, but it fails when trying to download curl, so I had to go through the built-in download and set it up manually

**Comment by KcrPL** [comment]
Can you please start cmd.exe as administrator and type:

`dism /online /cleanup-image /restorehealth`

This will check and eventually repair Windows files. To me it looks like few components are broken? Give it a try and let me know if it works after that.

**Comment by KcrPL** [comment]
Closing. Did not get an answer, probably due to corrupted OS.

**Comment by snowynoelle** [comment]
same for me, an help?
