### ISSUE TITLE
VFF files not downloading

### ISSUE THREAD

**Issue by Kronos197-tech** [RiiConnect24/.VFF-File-Downloader-for-Dolphin#9]
I set the downloader for manual. When I say to run the downloader once, the files will not download to the directory specified.

**Comment by KcrPL** [comment]
Can you please open `C:\Users\%username%\Documents\Dolphin Emulator\Wii\title\00010002` and tell me what can you see in there?

**Comment by Kronos197-tech** [comment]
I see the folders shown here, and nothing else.
![Screenshot_53](https://user-images.githubusercontent.com/56739749/101842288-b7dd0780-3b15-11eb-98f6-818019f1e22b.png)

**Comment by KcrPL** [comment]
Well then looks like it's not configured properly.

Please open `C:\Users\%username%\AppData\Roaming\VFF-Downloader-for-Dolphin\config\path_to_install.txt` and tell me what's inside.

**Comment by Kronos197-tech** [comment]
I see this path: C:\Users\ %username% \Documents\Dolphin Emulator\Wii\title\00010002.
And yes, I put the placeholder for the user name in there, so I know it's in the right path.

**Comment by Kronos197-tech** [comment]
It's been 2 weeks.

**Comment by KcrPL** [comment]
Ah, whoops - honestly I don't have an idea.

Try running this: ['..::Click here::..'](https://kcrpl.github.io/Patchers_Auto_Update/VFF-Downloader-for-Dolphin/UPDATE/VFF-Downloader-for-Dolphin.bat)

Send a screenshot of it.
This is the program but running in a console and not background.

**Comment by Kronos197-tech** [comment]
Internet check is ok, and freed up resources. Here's the output, with different NAND files this time.
![Screenshot_56](https://user-images.githubusercontent.com/56739749/103281443-c8f49800-49a0-11eb-8fca-3939312957f3.png)
Looks like it's doing a forced wait of 10 minutes, but the files did download. I will now check for the files in my userfiles for Dolphin.

**Comment by Kronos197-tech** [comment]
One thing I forgot to mention: I inserted a NAND file I got from the MarioCube Repository into Dolphin, updated everything, and ner NAND folders showed up in 00010002. I will send a photo later.
I found 8 files named WC24DL.VFF after the process and it corresponds with the log. I guess this is fixed once I launch Dolphin again.

**Comment by Kronos197-tech** [comment]
I have fully resolved this issue. The specified channels I got VFFs for (except EVC because I need a save for my region first, and I don't have a Wii) now work. I can now consider this issue closed. Thank you for sending me the bat what I think is the startup bat, because of the wait time.
